### ISSUE TITLE
This plugin does not support grails3.3.0

### ISSUE THREAD

**Issue by githubLixiaoyu** [grails-plugins/grails-spring-security-shiro#4]
This plugin does not support grails3.3.0

**Comment by andrelbuzzo** [comment]
Any chance to get a update of the plugin or to get this issue resolved?
Have been more than 3 months and still no solution 👎

**Comment by aadrian** [comment]
@andrelbuzzo this is a critical plug-in for many projects :(

**Comment by jameskleeh** [comment]
@githubLixiaoyu @andrelbuzzo @aadrian An example project with steps to reproduce is a great step forwarding to get the issue resolved. Also being more descriptive about what the actual problem is helps a lot.

**Comment by andrelbuzzo** [comment]
@jameskleeh Sorry for the lack of info, but many other Spring Security had this issue too, i.e. here: https://github.com/grails-plugins/grails-spring-security-cas/issues/20.

The error is:
java.lang.NoClassDefFoundError: org/springframework/boot/context/embedded/FilterRegistrationBean

A solution would be:
**>> Spring Boot 1.5.x removes a number of deprecated classes, notably all of the classes within the org.springframework.boot.context.embedded package.
> If your application is referencing any of the classes within this package you will need to alter your imports to use org.springframework.boot.web.servlet instead.**

**Comment by aadrian** [comment]
@jameskleeh  as @andrelbuzzo mentioned in the title, there's no need for detail steps: it's just not working **at all** :( .

**Comment by andrelbuzzo** [comment]
@sdelamo, @graemerocher, @burtbeckwith Any chance to help us solve this?
